'use client';

import {useEffect,useState} from 'react';

const CHAIN_ID=43114;
const contracts=[
 {name:'Aave V3 Flash Arbitrage',family:'Flashloan provider',file:'contracts/AaveV3FlashArbitrage.sol',description:'Single-provider round-trip flashloan template with repayment and profit-floor checks.'},
 {name:'Aave V3 Two-Router Arbitrage',family:'Flashloan + mixed venues',file:'contracts/archive/AaveV3TwoRouterArbitrage.sol',description:'Borrow one asset, swap through router A, reverse through router B, repay and enforce minimum profit.'},
 {name:'Liquidity Funded Executor',family:'No flashloan',file:'contracts/archive/LiquidityFundedExecutor.sol',description:'Owner-funded inventory executor for routes where capital is supplied by the contract owner.'},
 {name:'Mixed Liquidity / Multi-Provider',family:'Archive extension',file:'archive/README.md',description:'Architecture reserved for mixed funding and multiple flashloan-provider adapters; provider addresses must be verified before deployment.'}
];

export default function Page(){
 const [wallet,setWallet]=useState(''); const [chain,setChain]=useState(null); const [selected,setSelected]=useState(contracts[0]);
 const sync=async()=>{if(!window.ethereum)return; const accounts=await window.ethereum.request({method:'eth_accounts'}); const cid=await window.ethereum.request({method:'eth_chainId'}); setWallet(accounts[0]||''); setChain(parseInt(cid,16));};
 useEffect(()=>{sync(); if(window.ethereum){window.ethereum.on?.('accountsChanged',sync);window.ethereum.on?.('chainChanged',sync)} return()=>{window.ethereum?.removeListener?.('accountsChanged',sync);window.ethereum?.removeListener?.('chainChanged',sync)}},[]);
 const connect=async()=>{if(!window.ethereum){alert('Install an EIP-1193 wallet such as MetaMask or another supported wallet.');return} await window.ethereum.request({method:'eth_requestAccounts'}); try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0xA86A'}]})}catch(e){console.warn(e)} await sync()};
 const remix='https://remix.ethereum.org/';
 return <main className="shell">
  <header className="hero"><div className="eyebrow">AVALANCHE · C-CHAIN · 43114</div><h1>Flashloan + Remix Control Plane</h1><p className="muted">Archive, select, inspect and prepare Solidity strategies. Remix remains the authoritative IDE for compile, deployment and contract writes.</p><div className="actions"><button className="btn" onClick={connect}>{wallet?`Connected ${wallet.slice(0,6)}…${wallet.slice(-4)}`:'Connect Wallet'}</button><a className="btn secondary" href={remix} target="_blank" rel="noreferrer">Open Remix IDE ↗</a></div></header>
  <section className="grid"><div className="panel"><span className="pill">NETWORK</span><h2 className={chain===CHAIN_ID?'live':'gated'}>{chain===CHAIN_ID?'MAINNET READY':'CHAIN NOT CONFIRMED'}</h2><p className="muted">Detected chain: {chain??'—'} · Required: {CHAIN_ID}</p></div><div className="panel"><span className="pill">EXECUTION</span><h2 className="gated">GATED</h2><p className="muted">Explicit wallet and on-chain owner authorization required.</p></div><div className="panel"><span className="pill">ASSURANCE</span><h2>CONTROLLED</h2><p className="muted">Observe → Configure → Controlled Test → Ready → Live.</p></div><div className="panel"><span className="pill">CLOUD</span><h2>MONITORING</h2><p className="muted">Telemetry may observe; it never receives signing authority.</p></div></section>
  <section style={{marginTop:28}}><div className="panel"><div className="eyebrow">CONTRACT ARCHIVE</div><h2>Select a strategy family</h2><div className="grid">{contracts.map(c=><button key={c.name} className="panel strategy" onClick={()=>setSelected(c)}><span className="pill">{c.family}</span><strong>{c.name}</strong><span className="muted">{c.description}</span><span className="mono">{c.file}</span></button>)}</div></div></section>
  <section style={{marginTop:14}} className="panel"><div className="eyebrow">SELECTED CONTRACT</div><h2>{selected.name}</h2><p>{selected.description}</p><p className="mono">Source: {selected.file}</p><div className="actions"><a className="btn" href={remix} target="_blank" rel="noreferrer">Open in Remix</a><a className="btn secondary" href={`https://github.com/Samoolino/DAPP-REMIX-AVAX/blob/main/${selected.file}`} target="_blank" rel="noreferrer">View source ↗</a></div></section>
  <section style={{marginTop:14}} className="panel"><div className="eyebrow">EXECUTION PROCEDURE</div><div className="steps"><div className="step"><div><strong>OBSERVE</strong><div className="muted">Confirm Avalanche chain, wallet, provider, liquidity, token decimals, routes and current quotes.</div></div></div><div className="step"><div><strong>CONFIGURE</strong><div className="muted">Compile in Remix and configure exact deployed addresses, routers, assets and minimum outputs.</div></div></div><div className="step"><div><strong>CONTROLLED TEST</strong><div className="muted">Validate on Fuji or a controlled fork; verify repayment, events, gas and profit-floor behavior.</div></div></div><div className="step"><div><strong>READY</strong><div className="muted">Verify bytecode/source, owner, pause path, funding and monitoring before any mainnet write.</div></div></div><div className="step"><div><strong>LIVE</strong><div className="muted">Only the connected wallet signs a bounded transaction. No cloud flag or scanner can authorize spending.</div></div></div></div><div className="notice small">Safety gate: strategy templates do not guarantee profit. Provider addresses, liquidity, premiums, routes, slippage, gas and repayment must be independently verified at execution time.</div></section>
  <footer className="footer muted small">Vercel hosts this control plane. Remix performs Solidity compilation/deployment/interaction. Avalanche C-Chain performs the actual on-chain transaction. Never place private keys or service-role secrets in browser code.</footer>
 </main>
}
